[package]
name = "netxclient"
version = "1.4.0"
authors = ["luyi <luyikk@126.com>"]
edition = "2018"
repository = "https://github.com/luyikk/rust_netx"
documentation = "https://docs.rs/netxclient"
description = "netx client assembly."
license = "MIT/Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default=["tcp"]
tls=["openssl","openssl-sys","tokio-openssl"]
tcp=[]

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes="0.6"
log="0.4"
tcpclient = "1.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
paste="1.0"
aqueue="1.1"
async-trait="0.1"
data-rw="1.3"
async-oneshot = "0.4"
netxbuilder="1.1"
anyhow="1.0"
once_cell = "1.7"
cfg-if="1.0"
openssl = { version="0.10",optional = true}
openssl-sys = { version="0.9",optional = true}
tokio-openssl =  { version="0.6",optional = true}

[dev-dependencies]
env_logger = "0.8.2"
serde = { version = "1.0", features = ["derive"] }
log="0.4"
mimalloc = {version="0.1.25",default-features = false}
structopt = "0.3"