[package]
name = "netxclient"
version = "0.1.0"
authors = ["luyi <luyikk@126.com>"]
edition = "2018"
repository = "https://github.com/luyikk/rust_netx"
documentation = "https://docs.rs/netxclient"
description = "netx client assembly."
license = "MIT/Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes="0.6"
log="0.4"
tcpclient = "0.3.1"
serde = "1.0"
serde_json = "1.0"
paste="1.0.2"
aqueue="0.3.2"
data-rw="0.2.4"
async-oneshot = "0.4"
netxbuilder="0.1"

[dev-dependencies]
env_logger = "0.8.2"
serde = { version = "1.0", features = ["derive"] }