[package]
name = "netxclient"
version = "1.0.0"
authors = ["luyi <luyikk@126.com>"]
edition = "2018"
repository = "https://github.com/luyikk/rust_netx"
documentation = "https://docs.rs/netxclient"
description = "netx client assembly."
license = "MIT/Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes="0.6"
log="0.4"
tcpclient = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
paste="1.0"
aqueue="1.0"
async-trait="0.1"
data-rw="1.0"
async-oneshot = "0.4"
netxbuilder={path="../netx_builder"}
anyhow="1.0"

[dev-dependencies]
env_logger = "0.8.2"
serde = { version = "1.0", features = ["derive"] }
log="0.4"
mimalloc = {version="0.1.25",default-features = false}
structopt = "0.3"