[package]
name = "netxserver"
version = "0.1.0"
authors = ["yi lu <luyikk@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
tcpserver = "0.3.6"
aqueue="0.3.2"
log="0.4"
data-rw="0.2.4"
serde = "1.0"
paste="1.0.2"
bytes="0.6"
async-oneshot = "0.4"
netxbuilder={path="../netx_builder"}
chrono="0.4"

[dev-dependencies]
env_logger = "0.8.2"
serde = { version = "1.0", features = ["derive"] }