[package]
name = "netxserver"
version = "0.2.0"
authors = ["yi lu <luyikk@126.com>"]
edition = "2018"
repository = "https://github.com/luyikk/rust_netx"
documentation = "https://docs.rs/netxserver"
description = "netx server assembly."
license = "MIT/Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
tcpserver = "0.3"
aqueue="0.3"
log="0.4"
data-rw="0.3"
paste="1.0"
bytes="0.6"
async-oneshot = "0.4"
netxbuilder="0.2"
chrono="0.4"

[dev-dependencies]
env_logger = "0.8.2"
serde = { version = "1.0", features = ["derive"] }
log="0.4"
mimalloc = {version="0.1.25",default-features = false}